version: '3'
services:
  web:
    build: ./
    links:
        - db:postgres
    ports:
      - 5000:5000
  db:
    image: postgres:10.5
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
      - dblogs:/var/log/postgresql

volumes:
  dbdata:
  dblogs:
